#!/bin/bash

#
# Check if Homebrew is installed
#
which -s brew
if [[ $? != 0 ]] ; then
	# Install Homebrew
	# https://github.com/mxcl/homebrew/wiki/installation
	echo "Installing homebrew"
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
	echo "Updating homebrew"
	brew update
fi

brew install gcc
brew install pkg-config
brew install glew
brew install homebrew/versions/glfw3
brew install assimp
brew install devil
cp lib/irrKlang/libirrklang.dylib /usr/local/lib/
