#!/bin/bash

#
# Check if Homebrew is installed
#
which -s brew
if [[ $? != 0 ]] ; then
	# Install Homebrew
	# https://github.com/mxcl/homebrew/wiki/installation
	echo "Installing homebrew"
	/usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
else
	echo "Updating homebrew"
	brew update
fi

#
# Check if Git is installed
#
brew install pkg-config
brew install glew
brew install glfw3
brew install assimp
brew install devil
cp lib/irrKlang/libirrklang.dylib /usr/local/lib/
